# Generated by Django 5.1.2 on 2024-11-01 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
