# Generated by Django 5.1.2 on 2024-10-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(db_tablespace="valijon_tablespace", max_length=100),
        ),
    ]
