# Generated by Django 5.1.2 on 2024-11-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_delete_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
