# Generated by Django 5.1.2 on 2024-10-28 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_product1234"),
    ]

    operations = [
        migrations.CreateModel(
            name="Producttttt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
    ]
