# Generated by Django 5.1.2 on 2024-11-01 10:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0003_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_product_send_telegram", "Telegram userga productni yuborish")
                ]
            },
        ),
    ]
