# Generated by Django 5.1.2 on 2024-11-01 11:50

import django_jsonform.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AddField(
            model_name="product",
            name="data",
            field=django_jsonform.models.fields.JSONField(),
            preserve_default=False,
        ),
    ]
