# Generated by Django 5.1.2 on 2024-11-29 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_alter_productimage_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Film",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("released_date", models.DateField()),
                (
                    "genres",
                    models.ManyToManyField(related_name="films", to="apps.genre"),
                ),
            ],
        ),
    ]
