# Generated by Django 5.1.2 on 2024-11-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0005_alter_product_options_product_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="data",
        ),
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
