# Generated by Django 5.1.2 on 2024-11-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0007_film_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("begin", "Boshlandi"), ("end", "Tugadi")],
                default="begin",
                max_length=15,
            ),
        ),
    ]
